services:
  - type: web
    name: marine-safety-api
    env: python
    rootDir: backend
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: CARGO_HOME
        value: /opt/render/project/cargo
      - key: MONGO_URL
        sync: false
      - key: WEATHER_API_KEY
        sync: false
